name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -U coverage flake8
    - name: Run tests
      run: |
        coverage run --include "gcp_flowlogs_reader/*.py" -m unittest
    - name: Check coverage
      run: |
        coverage report --show-missing --fail-under=99.0
    - name: Lint with flake8
      run: |
        flake8 gcp_flowlogs_reader tests
    - name: Check formatting with black
      if: "matrix.python-version == '3.11'"
      run: |
        pip install -U black
        black --check .
    - name: Build packages
      if: "matrix.python-version == '3.11'"
      run: |
        pip install -U twine wheel
        python setup.py sdist bdist_wheel
        twine check dist/*
    - name: Upload packages
      if: "matrix.python-version == '3.11'"
      uses: actions/upload-artifact@v4
      with:
        name: gcp-flowlogs-reader-packages
        path: dist/*

  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      # https://docs.pypi.org/trusted-publishers/using-a-publisher/
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        name: gcp-flowlogs-reader-packages
        path: dist/
    - name: Upload packages to PyPi
      uses: pypa/gh-action-pypi-publish@release/v1
